name: Auto Generate script.py

on:
  push:
    paths:
      - 'configs/config.json'  # 仅当此文件发生变化时触发
      - 'templates/script_template.py.j2'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install jinja2

    - name: Run script generator
      run: python generate_script.py

    - name: Commit generated script.py
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add script.py
        git commit -m "🤖 Auto-generate script.py from config.json" || echo "No changes to commit"
        git push
